language: python

env:
    global:
        - PLAT=x86_64
        - UNICODE_WIDTH=32

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

services: docker
sudo: required

matrix:
    fast_finish: true
    exclude:
        - os: osx
    include:
        - os: linux
          compiler: clang
          env: MB_PYTHON_VERSION=3.6
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=2.7
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=3.4
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=3.5
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=3.6
        - os: linux
          compiler: gcc
          env: MB_PYTHON_VERSION=3.6

before_install:
    - unset -f pushd
    - unset -f popd
    - source external/multibuild/common_utils.sh
    - source external/multibuild/travis_steps.sh
    - before_install

install:
    - pip install setuptools setuptools-scm
    - pip install -r requirements.txt
    - git clone https://github.com/Statoil/libecl.git
    - mkdir libecl/build
    - pushd libecl/build
    - cmake .. -DBUILD_SHARED_LIBS=ON
               -DPYTHON_EXECUTABLE=`which python`
               -DENABLE_PYTHON=ON
    - sudo make install
    - popd

script:
    - echo $VIRTUAL_ENV
    - python -c "import setuptools;"
    - mkdir build
    - pushd build
    - cmake .. -DPYTHON_EXECUTABLE=`which python`
    - make
    - ctest --output-on-failure -VV
